services:
  behave-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: behave_container
    volumes:
      - .:/app
    working_dir: /app
    command: python behave_parallel/run_parallel.py
